server:
  port: 8700

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://121.4.211.127:3306/video_dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: root
    password: fangdai1W2
  redis:
    port: 6379
    host: 172.16.208.2
    password: fangdai1W2
    # 最大空闲连接数
    jedis:
      pool:
        max-active: 8
    # 最小空闲连接数
        max-idle: 8
    # 等待可用连接的最大时间，负数为不限制
        max-wait: -1
    # 最大活跃连接数，负数为不限制
        min-idle: 1
    # 数据库连接超时时间，2.0 中该参数的类型为Duration，这里在配置的时候需要指明单位  1.x可以将此参数配置10000 单位是ms
    # 连接池配置，2.0中直接使用jedis或者lettuce配置连接池
    timeout: 60s
    database: 0

  # 最大文件大小
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
minio:
  url: http://121.4.211.127:9000
  bucket: video
  access-key: admin
  secret-key: admin123456